#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#include QMK_KEYBOARD_CONFIG_H

#undef MOUSEKEY_DELAY
#undef MOUSEKEY_INTERVAL
#undef MOUSEKEY_MAX_SPEED
#undef MOUSEKEY_TIME_TO_MAX

#define MOUSEKEY_DELAY 40
#define MOUSEKEY_INTERVAL 40
#define MOUSEKEY_MAX_SPEED 30
#define MOUSEKEY_TIME_TO_MAX 20

#endif
