#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#include "../../config.h"

// fix iPhone power adapter issue
#define USB_MAX_POWER_CONSUMPTION 50

#undef MOUSEKEY_DELAY
#undef MOUSEKEY_INTERVAL
#undef MOUSEKEY_MAX_SPEED
#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_WHEEL_DELAY
#undef MOUSEKEY_WHEEL_MAX_SPEED
#undef MOUSEKEY_WHEEL_TIME_TO_MAX

#define MOUSEKEY_DELAY 40
#define MOUSEKEY_INTERVAL 40
#define MOUSEKEY_MAX_SPEED 30
#define MOUSEKEY_TIME_TO_MAX 20
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_MAX_SPEED 4
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0

#undef TAPPING_TOGGLE
#undef TAPPING_TERM
#undef PERMISSIVE_HOLD
#undef IGNORE_MOD_TAP_INTERRUPT

#define TAPPING_TOGGLE 1
#define TAPPING_TERM 300
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

#endif
